services:
  web:
    build: .
    container_name: catch-n-go
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./src:/src

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
